name: 001-ms-template

on:
  workflow_dispatch:

jobs:
  call-pipeline-workflow-A:
    uses: josue-r/Pipelines/.github/workflows/github-pipelines.yml@main
    with:
      username: Josue
    secrets:
      token: ${{ secrets.TOKEN }}

  call-pipeline-workflow-B:
    uses: josue-r/Pipelines/.github/workflows/github-pipelines.yml@main
    with:
      username: Vero
    secrets:
      token: ${{ secrets.TOKEN }}